import type { BaseEvent } from "@ag-ui/core";
import type { Observer } from "rxjs";
import type { LanguageModel, UIMessage } from "ai";
import type { MockAuthSession } from "@/lib/auth/session";
import { buildManagerConversationPrompt } from "@/agents/manager/prompt/conversation";
import { resolveAgentTools } from "@/agents/config";
import { emitState, emitInterrupt, type PendingToolCall } from "./ag-ui-types";
import { streamSpecialistEvents } from "./ag-ui-stream";
import { getTextParts } from "@/utils/message";

const MUTATION_TOOL_LABELS: Record<string, string> = {
  approve_team_time_off_request: "Approve time-off request",
  reject_team_time_off_request: "Reject time-off request",
};

// Detects the exact format generated by buildTeamActionPrompt in cells.tsx:
// "Approve/Reject {requestQuery}. Reason/Comment: {comment}."
function tryParseDirectMutationPrompt(
  text: string,
  session: MockAuthSession,
): Omit<PendingToolCall, "specialist"> | null {
  const match = text
    .trim()
    .match(/^(Approve|Reject)\s+(.+?)\.\s*(?:Reason|Comment):\s*(.+?)\.?\s*$/i);
  if (!match) return null;

  const isReject = /^reject$/i.test(match[1].trim());
  const requestQuery = match[2].trim();
  const comment = match[3].trim();
  const name = isReject
    ? "reject_team_time_off_request"
    : "approve_team_time_off_request";

  // Look for the employee in managed employees to attach metadata (email/avatar)
  const lowerQuery = requestQuery.toLowerCase();
  const employee = session.managedEmployees.find((e) =>
    lowerQuery.includes(e.name.toLowerCase()),
  );

  return {
    name,
    args: {
      requestQuery,
      comment,
      showTeamPending: true,
      employeeEmail: employee?.email,
      employeeAvatar: employee?.avatar,
    },
    label: MUTATION_TOOL_LABELS[name] ?? name,
  };
}

// Detects past-tense mutation language in model responses (model bypassed the tool)
const MUTATION_RESPONSE_PATTERNS = [
  /\bI(?:'ve| have)\s+(?:gone\s+ahead\s+and\s+)?rejected\b/i,
  /\bI(?:'ve| have)\s+(?:gone\s+ahead\s+and\s+)?approved\b/i,
  /\brejected\s+(?:the|this|their)\s+(?:request|leave)\b/i,
  /\bapproved\s+(?:the|this|their)\s+(?:request|leave)\b/i,
];

function hasMutationInResponse(text: string): boolean {
  return MUTATION_RESPONSE_PATTERNS.some((p) => p.test(text));
}

export async function runManagerFlow(
  observer: Observer<BaseEvent>,
  runId: string,
  uiMessages: UIMessage[],
  session: MockAuthSession,
  model: LanguageModel,
  additionalInstructions?: string,
): Promise<void> {
  emitState(observer, { phase: "executing", specialist: "manager" });

  // Pre-stream: if the latest user message matches the table action button format
  // (e.g. "Reject Mia Nguyen Annual leave 2026-05-12 to 2026-05-13. Reason: Not approved.")
  // skip the model entirely and trigger HITL directly
  const lastUserMsg = [...uiMessages].reverse().find((m) => m.role === "user");
  const lastUserText = lastUserMsg ? getTextParts(lastUserMsg).join("\n").trim() : "";
  const directMutation = tryParseDirectMutationPrompt(lastUserText, session);

  if (directMutation) {
    emitInterrupt(observer, "manager", directMutation);
    return;
  }

  // Normal model-driven flow with HITL interrupt support
  let interruptFired = false;
  let accumulatedText = "";

  const baseManagerPrompt = buildManagerConversationPrompt(session);

  await streamSpecialistEvents(observer, {
    runId,
    model,
    uiMessages,
    baseSystemPrompt: additionalInstructions
      ? `${baseManagerPrompt}\n\n${additionalInstructions}`
      : baseManagerPrompt,
    tools: resolveAgentTools("manager", session, undefined, model),
    onTextDelta: (delta) => { accumulatedText += delta; },
    onInterrupt: ({ name, args, label }) => {
      interruptFired = true;
      emitInterrupt(observer, "manager", { name, args, label });
    },
  });

  // Post-stream fallback: if the model described a mutation without calling the tool,
  // try to reconstruct HITL intent from the original user message
  if (!interruptFired && hasMutationInResponse(accumulatedText)) {
    const fallbackMutation = tryParseDirectMutationPrompt(lastUserText, session);
    if (fallbackMutation) {
      emitInterrupt(observer, "manager", fallbackMutation);
    }
  }
}
